# Generated by Django 2.2.16 on 2022-08-08 15:01

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(choices=[('gram', 'г'), ('item', 'шт'), ('tablespoon', 'ст/л'), ('tea_spoon', 'ч/л'), ('pinch', 'щепотка'), ('taste', 'по вкусу')], max_length=255, verbose_name='Единица измерения')),
                ('amount', models.IntegerField(verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=1, validators=[core.validators.cooking_time_validator], verbose_name='Время приготовления'),
            preserve_default=False,
        ),
    ]
