# Generated by Django 2.2.16 on 2022-08-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220809_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('gram', 'г'), ('item', 'шт'), ('tablespoon', 'ст. л.'), ('mililiter', 'мл'), ('tea_spoon', 'ч. л.'), ('pinch', 'щепотка'), ('taste', 'по вкусу')], max_length=255, verbose_name='Единица измерения'),
        ),
    ]
