# Generated by Django 2.2.16 on 2022-08-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeIngredient', to='recipes.Ingredient'),
        ),
        migrations.DeleteModel(
            name='AmountIngredient',
        ),
    ]
